core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views import generic

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),

    # password_reset
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/passwd/reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/passwd/reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/passwd/reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/passwd/reset_complete.html'),
         name='password_reset_complete'),
    # end password_reset
    path('', generic.TemplateView.as_view(
        template_name='index.html'), name='index')
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import (ProductDetailView,
                    ProductListView,
                    ProductCreateView,
                    ProductUpdateView,
                    ProductDeleteView,
                    ImageCreateView,
                    ImageEditView,
                    ImageDeleteView)

app_name = 'products'
urlpatterns = [
    path('all/',
         ProductListView.as_view(),
         name='all'),
    path('create/',
         ProductCreateView.as_view(),
         name='create'),
    path('detail/<int:pk>/',
         ProductDetailView.as_view(),
         name='detail'),
    path('edit/<int:pk>/',
         ProductUpdateView.as_view(),
         name='edit'),
    path('delete/<int:pk>/',
         ProductDeleteView.as_view(),
         name='delete'),
    path('category/<str:cat_slug>/',
         ProductListView.as_view(),
         name='by_category'),
    path('image-create/<int:pk>/',
         ImageCreateView.as_view(),
         name="image_create"),
    path('edit-image/<int:pk>/',
         ImageEditView.as_view(),
         name="image_edit"),
    path('edit-delete/<int:pk>/',
         ImageDeleteView.as_view(),
         name="image_delete")
]

products/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.core.validators import (MinValueValidator,
                                    MaxValueValidator)
from django.utils import timezone
from decimal import Decimal
from mptt.models import MPTTModel, TreeForeignKey
from .utils import City

User = get_user_model()


class Category(MPTTModel):
    """
    Product category class
    """
    image = models.ImageField("Лого категории",
                              default="category_img/defoult.png",
                              upload_to="category_img")
    name = models.CharField("Название",
                            max_length=300)
    slug = models.SlugField("Url",
                            max_length=300,
                            unique=True)
    parent = TreeForeignKey("self",
                            on_delete=models.CASCADE,
                            null=True,
                            blank=True,
                            related_name='children',
                            verbose_name="Категория верхнего уровня")
    is_active = models.BooleanField("Статус",
                                    default=True)

    class MPTTMeta:
        order_insertion_by = ['slug']

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:by_category",
                       kwargs={"slug": self.slug})


class Product(models.Model):
    """
    Product class
    """

    name = models.CharField("Название", max_length=300)
    price = models.DecimalField("Цена",
                                max_digits=10,
                                decimal_places=2,
                                default=0)
    discount = models.IntegerField("Дисконт",
                                   default=0,
                                   validators=[MinValueValidator(0),
                                               MaxValueValidator(100)])
    main_image = models.ImageField("Изображение",
                                   upload_to="product_img")
    video = models.URLField("Ссылка на видео",
                            null=True,
                            blank=True)
    owner = models.ForeignKey(User,
                              on_delete=models.CASCADE,
                              related_name="products",
                              verbose_name="Владелец")
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE,
                                 related_name='products',
                                 verbose_name="Категория")
    overview = models.TextField("Описание",
                                max_length=2000)
    is_active = models.BooleanField("Статус",
                                    default=False)
    timestamp = models.DateTimeField("Дата добавления",
                                     default=timezone.now)
    city = models.CharField("Город",
                            max_length=20,
                            choices=City.CITY_LIST,
                            default=City.ANY)

    class Meta:
        verbose_name = "Товар/Акция"
        verbose_name_plural = "Товары/Акции"
        ordering = ('-timestamp',)

    def price_after_discount(self):
        return self.price - self.price * \
            (self.discount / Decimal('100'))

    def get_absolute_url(self):
        return reverse("products:detail",
                       kwargs={"pk": self.pk})


class Image(models.Model):
    product = models.ForeignKey(Product,
                                on_delete=models.CASCADE,
                                related_name="images")
    image = models.ImageField("Изображение",
                              upload_to="product_img")
    is_active = models.BooleanField("Статус",
                                    default=True)
    timestamp = models.DateTimeField("Дата добавления",
                                     default=timezone.now)

    class Meta:
        verbose_name = "Дополнительное фото"
        verbose_name_plural = "Дополнительные фото"

    def __str__(self):
        return f"{self.product.id}"


class Slider(models.Model):
    img = models.ImageField(upload_to="slider")

    class Meta:
        verbose_name = 'Слайдер'
        verbose_name_plural = 'Слайдеры'


class Feedback(models.Model):
    product = models.ForeignKey(Product,
                                on_delete=models.CASCADE,
                                related_name="feedbacks",
                                verbose_name="Товар/Акция",
                                null=True,
                                blank=True)
    sender = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name="feed_sender",
                               verbose_name="Отправитель")
    receiver = models.ForeignKey(User,
                                 on_delete=models.CASCADE,
                                 related_name="feed_receiver",
                                 verbose_name="Кому")
    text = models.TextField("Текст",
                            max_length=600)
    timestamp = models.DateTimeField("Время",
                                     default=timezone.now)

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

    def __str__(self):
        return f"{self.sender.email} at {self.timestamp}"

products/forms.py
from django import forms
from .models import Product, Image


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        exclude = ('is_active', 'owner', 'timestamp')


class ImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ('image',)

products/views.py
from django.shortcuts import get_object_or_404
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Category, Product, Image
from .forms import ProductForm, ImageForm
from .mixins import IsOwnerMixin
from django.http import Http404


class ImagePermissionsMixin:
    def get(self, *args, **kwargs):
        product = self.get_object().product
        if not self.request.user == product.owner:
            raise Http404
        return super().get(*args, **kwargs)


class ProductListView(generic.ListView):
    """
    product list queryset can be a filtered by category
    name, or include all products ordered by creation date
    """
    model = Product
    template_name = 'products/list.html'
    paginate_by = 16

    def get_queryset(self, **kwargs):
        category = None
        qs = super().get_queryset()
        cat_slug = self.kwargs.get('cat_slug')
        if cat_slug:
            """
            use get_descendants() to include all children's
            category products in queryset
            """
            category = get_object_or_404(
                Category,
                slug=cat_slug).get_descendants(include_self=True)
            qs = qs.filter(category__in=category)
        return qs


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'products/detail.html'


class ProductCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = ProductForm
    template_name = 'products/create.html'
    success_url = reverse_lazy('products:all')

    def form_valid(self, form):
        if form.is_valid():
            p_form = form.save(commit=False)
            p_form.owner = self.request.user
            p_form.save()
            return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin,
                        IsOwnerMixin,
                        generic.UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/edit.html'

    def get_success_url(self):
        return reverse_lazy('products:detail',
                            args=[self.get_object().pk])


class ProductDeleteView(LoginRequiredMixin,
                        IsOwnerMixin,
                        generic.DeleteView):
    model = Product
    template_name = 'products/delete.html'
    success_url = reverse_lazy('products:all')


class ImageCreateView(LoginRequiredMixin, generic.CreateView):
    model = Image
    form_class = ImageForm
    template_name = 'products/image_create.html'

    def get(self, *args, **kwargs):
        product = Product.objects.get(pk=self.kwargs['pk'])
        if not self.request.user == product.owner:
            raise Http404
        return super().get(*args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('products:detail',
                            args=[self.kwargs['pk']])

    def form_valid(self, form):
        if form.is_valid:
            new = form.save(commit=False)
            new.product = Product.objects.get(pk=self.kwargs['pk'])
            new.save()
            return super().form_valid(form)


class ImageEditView(LoginRequiredMixin,
                    ImagePermissionsMixin,
                    generic.UpdateView):
    model = Image
    form_class = ImageForm
    template_name = 'products/image_edit.html'

    def form_valid(self, form):
        if form.is_valid():
            new = form.save(commit=False)
            new.product = self.get_object().product
            new.save()
            return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('products:detail',
                            args=[self.get_object().product.pk])


class ImageDeleteView(LoginRequiredMixin,
                      ImagePermissionsMixin,
                      generic.DeleteView):
    model = Image
    template_name = 'products/image_delete.html'
    success_url = reverse_lazy('products:all')

    def get_success_url(self):
        return reverse_lazy('products:detail',
                            args=[self.get_object().product.pk])

templates/products/create.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center my-5">
        <div class="col-lg-6">
            <h3>Create new product here:</h3>
            <form method="POST" enctype="multipart/form-data">{% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-outline-success" type="submit">Create</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/products/delete.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <form method="post">{% csrf_token %}
                {{ form }}
                <p>Do you realy want to delete this product?</p>
                <button type="submit">Yes</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/products/detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row mt-5">
    <div class="col-lg-6">
      <img class="img-fluid" src="{{ object.main_image.url }}" alt="" />
      <div class="row mt-3">
        {% for img in object.images.all %}
          <div class="col-lg-3">
            <a {% if request.user == object.owner %}
                  href="{% url 'products:image_edit' pk=img.pk %}"
                {% else %}
                  href="#"
                {% endif %}>
              <img class="img-fluid" src="{{ img.image.url }}" alt="">
            </a>
          </div>
        {% endfor %}
      </div>
      {% if request.user == object.owner %}
        <div class="row mt-5 justify-content-center">
          <a class="btn btn-outline-success" href="{% url 'products:image_create' pk=object.pk %}">add image</a>
        </div>
      {% endif %}
    </div>
    <div class="col-lg-6">
      <h3>{{ object.name }}</h3>
      <h5>{{ object.owner.email }}</h5>
      <a href="{% url 'products:by_category' object.category.slug %}">
        {{ object.category.name }}
      </a>
      {% if object.discount > 0 %}
        <p><strike>{{ object.price }}</strike></p>
        <h5>{{ object.price_after_discount }}</h5>
      {% else %}
        <h5>{{ object.price }}</h5>
      {% endif %}
      <p>{{ object.overview }}</p>
    </div>
  </div>
</div>

{% endblock content %}

templates/products/edit.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <form  method="POST" enctype="multipart/form-data">{% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/products/image_create.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center my-5">
        <div class="col-lg-6">
            <h3>Add new image</h3>
            <form method="POST" enctype="multipart/form-data">{% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-outline-success" type="submit">Create</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/products/image_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <form method="post">{% csrf_token %}
                {{ form }}
                <p>Do you realy want to delete this product?</p>
                <button type="submit">Yes</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/products/image_edit.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center my-5">
        <div class="col-lg-6">
            <h3>Add new image</h3>
            <form method="POST" enctype="multipart/form-data">{% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-outline-success" type="submit">Create</button>
            </form>
        </div>
    </div>
    <a href="{% url 'products:image_delete' object.pk %}">Delete Option</a>
</div>

{% endblock content %}

templates/products/list.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="row ">
        {% for item in object_list %}
        <div class="col-lg-3 mt-5 ">
          <div class="card h-100 p-2">
            <img class="img-fluid" src="{{ item.main_image.url }}" alt="" />
            <a href="{{ item.get_absolute_url }}">{{ item.name }}</a>
            {% if item.discount == 0 %}
            <p>{{ item.price }} uah</p>
            {% else %}
            <div>
              <strike>{{ item.price }} uah</strike>
              <p>{{ item.price_after_discount }} uah</p>
            </div>
            {% endif %} {{ item.owner.email }}{{ item.timestamp }}
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>


{% comment %} {% load mptt_tags %}
<ul>
  {% recursetree categories %}
  <li>
    <a href="{% url 'products:by_category' node.slug %}">
      {{ node.name }}
    </a>
    {% if not node.is_leaf_node %}
    <ul class="children">
      {% for c in node.get_children %}
      <li>
        <a href="{% url 'products:by_category' c.slug %}"> {{ c }} </a>
      </li>
      {% endfor %}
    </ul>
    {% endif %}
  </li>
  {% endrecursetree %}
</ul> {% endcomment %}

{% endblock content %}