core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views import generic

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),

    # password_reset
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/passwd/reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/passwd/reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/passwd/reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/passwd/reset_complete.html'),
         name='password_reset_complete'),
    # end password_reset
    path('', generic.TemplateView.as_view(
        template_name='index.html'), name='index')
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import (ProductDetailView,
                    ProductListView,
                    ProductCreateView,
                    ProductUpdateView,
                    ProductDeleteView,
                    ImageCreateView,
                    ImageEditView,
                    ImageDeleteView)

app_name = 'products'
urlpatterns = [
    path('all/',
         ProductListView.as_view(),
         name='all'),
    path('create/',
         ProductCreateView.as_view(),
         name='create'),
    path('detail/<int:pk>/',
         ProductDetailView.as_view(),
         name='detail'),
    path('edit/<int:pk>/',
         ProductUpdateView.as_view(),
         name='edit'),
    path('delete/<int:pk>/',
         ProductDeleteView.as_view(),
         name='delete'),
    path('category/<str:cat_slug>/',
         ProductListView.as_view(),
         name='by_category'),
    path('image-create/<int:pk>/',
         ImageCreateView.as_view(),
         name="image_create"),
    path('edit-image/<int:pk>/',
         ImageEditView.as_view(),
         name="image_edit"),
    path('edit-delete/<int:pk>/',
         ImageDeleteView.as_view(),
         name="image_delete")
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (SignUpView,
                    ActivationView,
                    profile,
                    CustomPasswordChangeView)


app_name = 'users'
urlpatterns = [
    path('new/', SignUpView.as_view(), name='new'),
    path('login/', auth_views.LoginView.as_view(
        template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='users/logout.html'), name="logout"),
    path('profile/', profile, name="profile"),
    path('activate/<uidb64>/<token>/',
         ActivationView.as_view(), name='activate'),
    path('passwd-change/',
         CustomPasswordChangeView.as_view(), name='passwd_change'),
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    {% include 'nav.html' %}
    {% if messages %}                
        <div class="container">
            <div class="row mt-3 justify-content-center">
                <div class="col-lg-5">
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
    {% block content %}{% endblock content %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  </body>
</html>

templates/nav.html
{% comment %} {% load products_tags %} {% endcomment %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<div class="container">
  {% comment %} <a class="navbar-brand" href="#">Logo</a> {% endcomment %}
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="col-lg-3 mr-4"></div><div class="col-lg-5 ml-1"><ul class="navbar-nav">
      {% comment %} <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% cat_list as categories %}
          {% for cat in categories %}
            <a href="{% url 'products:by_category' cat.slug %}" class="dropdown-item" >
              {% if cat.parent %}-- {{ cat.name }}{{ cat.get_level }}{% else %}{{ cat.name }}{% endif %}
            </a>
          {% endfor %}
        </div>
      </li> {% endcomment %}
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link mr-3" href="{% url 'users:logout' %}" tabindex="-1" aria-disabled="true">
            Выход
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:profile' %}">Профиль</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link mr-3" href="{% url 'users:login' %}" tabindex="-1" aria-disabled="true">
              Вход
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:new' %}">Регистрация</a>
        </li>
      {% endif %}
    </ul>
    </div>
    <div class="col-lg-4"></div>
    {% comment %} <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> {% endcomment %}
  </div>
</div>
</nav>