core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views import generic

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),

    # password_reset
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/passwd/reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/passwd/reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/passwd/reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/passwd/reset_complete.html'),
         name='password_reset_complete'),
    # end password_reset
    path('', generic.TemplateView.as_view(
        template_name='index.html'), name='index')
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (SignUpView,
                    ActivationView,
                    profile,
                    CustomPasswordChangeView)


app_name = 'users'
urlpatterns = [
    path('new/', SignUpView.as_view(), name='new'),
    path('login/', auth_views.LoginView.as_view(
        template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='users/logout.html'), name="logout"),
    path('profile/', profile, name="profile"),
    path('activate/<uidb64>/<token>/',
         ActivationView.as_view(), name='activate'),
    path('passwd-change/',
         CustomPasswordChangeView.as_view(), name='passwd_change'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import CustomUserManager
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from products.utils import City

User = settings.AUTH_USER_MODEL


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField('Почта', unique=True)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(CustomUser,
                                primary_key=True,
                                related_name='profile',
                                on_delete=models.CASCADE)
    image = models.ImageField("Фото профиля",
                              upload_to="profile_img",
                              default="profile_img/default_profile_img.jpg"
                              )

    brand = models.CharField("Бренд",
                             max_length=100,
                             null=True,
                             blank=True)
    city = models.CharField("Город",
                            choices=City.CITY_LIST,
                            max_length=50,
                            null=True,
                            blank=True)
    address = models.CharField("Адресс",
                               max_length=300,
                               null=True,
                               blank=True)
    phone = models.CharField("Телефон",
                             max_length=100,
                             null=True,
                             blank=True)

    def __str__(self):
        return self.user.email

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from .models import CustomUser, Profile


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email', 'password1', 'password2')


class CustomUserEditForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('first_name', 'email')


class UserEditForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name')


class ProfileEditForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('image', 'brand', 'city', 'address', 'phone')

users/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, View
from django.urls import reverse_lazy
from django.core.mail import EmailMessage
from django.contrib.auth import get_user_model, login
from django.contrib.auth.views import (PasswordChangeView,
                                       PasswordResetView,
                                       PasswordResetConfirmView)
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .forms import (CustomUserCreationForm,
                    UserEditForm,
                    ProfileEditForm)
from .tokens import account_activation_token
from django.contrib import messages
from django.contrib.auth.decorators import login_required

User = get_user_model()


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/registration.html'

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        current_site = get_current_site(self.request)
        mail_subject = 'Активация нового пользователя'
        message = render_to_string('users/activation/message.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': account_activation_token.make_token(user),
        })
        to_email = form.cleaned_data.get('email')
        email = EmailMessage(mail_subject,
                             message,
                             to=[to_email])
        email.send()
        messages.success(self.request,
                         """Проверьте указанный при регистрации email адресс. 
            Мы отправили вам сообщение с дальнейшими инструкциями.""")
        return super().form_valid(form)


class ActivationView(View):
    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist) as e:
            user = None
            print(e)
        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            messages.success(
                request, "Ваш профиль успешно зарегистрирован.")
            return redirect('users:profile')
        else:
            messages.warning(
                request, "Ошибка прав доступа! Возможно введены не верные данные.")
        return redirect('users:login')


@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UserEditForm(request.POST,
                                 instance=request.user)
        profile_form = ProfileEditForm(request.POST,
                                       request.FILES,
                                       instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('users:profile')
    user_form = UserEditForm(instance=request.user)
    profile_form = ProfileEditForm(instance=request.user.profile)
    context = {'user_form': user_form,
               'profile_form': profile_form}
    return render(request, 'users/profile.html', context)


class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'users/passwd/change.html'
    success_url = reverse_lazy('users:profile')

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "Пароль был успешно изменен.")
        return super().form_valid(form)

templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-5">
            <h3 class="mt-4 text-right">Авторизация</h3>
            <hr>
            <form class="mt-4" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-outline-info" type="submit">Войти</button>
            </form>
            <div class="mt-4 text-right">
                <p>Впервые у нас? <a href="{% url 'users:new' %}">Регистрация</a></p>
                <a href="{% url 'password_reset' %}">Забыли пароль?</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/users/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row justify-content-center my-4">
        <div class="col-lg-5">
            <h3 class="text-right">Личная информация</h3>
            <hr>
            <div class="text-right">
                <img class="img-fluid rounded-circle border" src="{{ request.user.profile.image.url }}" alt="" style="max-height: 150px">
            </div>
            <form class="mt-4" action="." method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form|crispy }}
                {{ profile_form|crispy }}
                <button type="submit" class="btn btn-outline-info">Сохранить</button>
            </form>
            <h3 class="mt-5 text-right">Безопасность</h3>
            <hr>
            <p class="mt-4">Для смены пароля перейдите по ссылке ниже:</p>
            <a href="{% url 'users:passwd_change' %}">Изменить пароль</a>
        </div>
    </div>
</div>
{% endblock content %}

templates/users/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row justify-content-center my-4">
        <div class="col-lg-5">
            <h3 class="text-right">Новый пользователь</h3>
            <hr>
            <form class="mt-4" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-outline-info" type="submit">Создать</button>
            </form>
            <div class="text-right">
                <p>Уже есть профиль? Авторизуйтесь по <a href="{% url 'users:login' %}">ссылке</a></p>
                <a href="{% url 'password_reset' %}">Восстановление доступа</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}